CREATE TABLE IF NOT EXISTS "conference" (
    "conference" CHAR(3) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS "division" (
    "division" VARCHAR(5),
    "conference" CHAR(3) REFERENCES "conference",
    PRIMARY KEY("division", "conference")
);

CREATE TABLE IF NOT EXISTS "team" (
    "team_id" INT PRIMARY KEY,
    "team_name" VARCHAR(30) NOT NULL,
    "abbreviation" VARCHAR(3) NOT NULL,
    "conference" CHAR(3) NOT NULL,
    "division" VARCHAR(5) NOT NULL,
    foreign KEY ("division", "conference") REFERENCES "division"
);

CREATE TABLE IF NOT EXISTS "season" (
    "season_id" INT GENERATED BY DEFAULT AS IDENTITY (start with 2025) PRIMARY KEY,
    "start_date" DATE NOT NULL,
    "end_date" DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "game" (
    "game_id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "week" INT NOT NULL,
    "is_outside" BOOL NOT NULL,
    "bad_weather" BOOL NOT NULL,
    "is_neutral" BOOL DEFAULT false,
    "game_date" DATE NOT NULL,
    "season_id" INT REFERENCES "season" NOT NULL, 
    "home_team_id" INT REFERENCES "team" NOT NULL,
    "away_team_id" INT REFERENCES "team" NOT NULL,
    "home_team_score" INT NOT NULL,
    "away_team_score" INT NOT NULL,

    constraint different_teams
    CHECK( "home_team_id" <> "away_team_id")
);

CREATE TABLE IF NOT EXISTS "position" (
    "position" VARCHAR(2) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS "player" (
    "player_id" INT PRIMARY KEY,
    "full_name" VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS "player_position" (
    "player_id" INT REFERENCES "player",
    "position" VARCHAR(2) REFERENCES "position",
    PRIMARY KEY("player_id", "position")
);

CREATE TABLE IF NOT EXISTS "roster" (
    "roster_id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "player_id" INT NOT NULL REFERENCES "player",
    "team_id" INT NOT NULL REFERENCES "team",
    "start_date" DATE NOT NULL,
    "end_date" DATE,

    constraint valid_date_range
    CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS "season_team_stats"(
    "team_id" INT REFERENCES "team",
    "season_id" INT REFERENCES "season",
    "regular_season" BOOL DEFAULT true,
    PRIMARY KEY ("team_id", "season_id", "regular_season"),

    -- Scoring
    "total_points" INT NOT NULL,
    "total_touchdowns" INT NOT NULL,

    -- First Downs
    "first_downs_rushing" INT NOT NULL,
    "first_downs_passing" INT NOT NULL,
    "first_downs_penalty" INT NOT NULL,

    -- Third Down
    "third_down_attempts" INT NOT NULL,
    "third_down_conversions" INT NOT NULL,

    -- Fourth Down
    "fourth_down_attempts" INT NOT NULL,
    "fourth_down_conversions" INT NOT NULL,

    -- Passing
    "pass_completions" INT NOT NULL,
    "pass_attempts" INT NOT NULL,
    "net_passing_yards" INT NOT NULL,
    "passing_touchdowns" INT NOT NULL,
    "interceptions_thrown" INT NOT NULL,
    "sacks" INT NOT NULL,
    "sack_yards_lost" INT NOT NULL,

    -- Rushing
    "rushing_attempts" INT NOT NULL,
    "rushing_yards" INT NOT NULL,
    "rushing_touchdowns" INT NOT NULL,

    -- Offense
    "offensive_plays" INT NOT NULL,
    "total_yards" INT NOT NULL,

    -- Returns
    "kickoff_returns" INT NOT NULL,
    "kickoff_return_yards" INT NOT NULL,
    "punt_returns" INT NOT NULL,
    "punt_return_yards" INT NOT NULL,
    "interception_returns" INT NOT NULL,
    "interception_return_yards" INT NOT NULL,

    -- Kicking
    "punts" INT NOT NULL,
    "punt_total_yards" INT NOT NULL,
    "field_goals_made" INT NOT NULL,
    "field_goals_attempted" INT NOT NULL,
    "touchbacks" INT NOT NULL,

    -- Penalties
    "penalties_count" INT NOT NULL,
    "penalty_yards" INT NOT NULL,

    -- Time of Possession
    "possession_time_seconds" INT NOT NULL,

    -- Miscellaneous
    "fumbles" INT NOT NULL,
    "fumbles_lost" INT NOT NULL,
    "turnovers" INT NOT NULL
);

CREATE TABLE IF NOT EXISTS "game_team_stats" (
    "game_id" INT NOT NULL REFERENCES "game",
    "team_id" INT NOT NULL REFERENCES "team",

    -- 1st Downs
    "first_downs_total" INT NOT NULL CHECK ("first_downs_total" >= 0),
    "first_downs_passing" INT NOT NULL CHECK ("first_downs_passing" >= 0),
    "first_downs_rushing" INT NOT NULL CHECK ("first_downs_rushing" >= 0),
    "first_downs_penalty" INT NOT NULL CHECK ("first_downs_penalty" >= 0),

    -- 3rd Down
    "third_down_conversions" INT NOT NULL CHECK ("third_down_conversions" >= 0),
    "third_down_attempts" INT NOT NULL CHECK ("third_down_attempts" >= 0),
    CHECK ("third_down_conversions" <= "third_down_attempts"),

    -- 4th Down
    "fourth_down_conversions" INT NOT NULL CHECK ("fourth_down_conversions" >= 0),
    "fourth_down_attempts" INT NOT NULL CHECK ("fourth_down_attempts" >= 0),
    CHECK ("fourth_down_conversions" <= "fourth_down_attempts"),

    -- Offense
    "total_plays" INT NOT NULL CHECK ("total_plays" >= 0),
    "total_yards" INT NOT NULL,

    "total_drives" INT NOT NULL CHECK ("total_drives" >= 0),

    -- Passing
    "passing_yards" INT NOT NULL,
    "pass_completions" INT NOT NULL CHECK ("pass_completions" >= 0),
    "pass_attempts" INT NOT NULL CHECK ("pass_attempts" >= 0),
    CHECK ("pass_completions" <= "pass_attempts"),

    "interceptions_thrown" INT NOT NULL CHECK ("interceptions_thrown" >= 0),

    "sacks" INT NOT NULL CHECK ("sacks" >= 0),
    "sack_yards_lost" INT NOT NULL CHECK ("sack_yards_lost" >= 0),

    -- Rushing
    "rushing_yards" INT NOT NULL,
    "rushing_attempts" INT NOT NULL CHECK ("rushing_attempts" >= 0),

    -- Red Zone
    "red_zone_made" INT NOT NULL CHECK ("red_zone_made" >= 0),
    "red_zone_attempts" INT NOT NULL CHECK ("red_zone_attempts" >= 0),
    CHECK ("red_zone_made" <= "red_zone_attempts"),

    -- Penalties
    "penalties_count" INT NOT NULL CHECK ("penalties_count" >= 0),
    "penalty_yards" INT NOT NULL CHECK ("penalty_yards" >= 0),

    -- Turnovers
    "turnovers" INT NOT NULL CHECK ("turnovers" >= 0),
    "fumbles_lost" INT NOT NULL CHECK ("fumbles_lost" >= 0),

    -- Defense / Special Teams
    "defensive_special_teams_tds" INT NOT NULL CHECK ("defensive_special_teams_tds" >= 0),

    -- Time of Possession (seconds in full "game")
    "possession_time_seconds" INT NOT NULL CHECK (
        "possession_time_seconds" >= 0
        AND "possession_time_seconds" <= 3600
    ),

    PRIMARY KEY ("game_id", "team_id")
);

-- Main TABLE
CREATE TABLE IF NOT EXISTS "season_player_stats" (
    "season_id" INT NOT NULL REFERENCES "season"("season_id"),
    "player_id" INT NOT NULL REFERENCES "player"("player_id"),
    "is_regular_season" BOOL NOT NULL,
    "team_id" INT NOT NULL REFERENCES "team"("team_id"),
    PRIMARY KEY ("season_id", "player_id", "is_regular_season")
);

-- Receiving Stats
CREATE TABLE IF NOT EXISTS "season_player_receiving_stats" (
    "season_id" INT NOT NULL,
    "player_id" INT NOT NULL,
    "is_regular_season" BOOL NOT NULL,
    "gp" INT NOT NULL,
    "rec" INT NOT NULL,
    "tgts" INT NOT NULL,
    "yds" INT NOT NULL,
    "avg" NUMERIC(6,2) NOT NULL,
    "td" INT NOT NULL,
    "lng" INT NOT NULL,
    "fd" INT NOT NULL,
    "fum" INT NOT NULL,
    "lst" INT NOT NULL,
    PRIMARY KEY ("season_id", "player_id", "is_regular_season"),
    FOREIGN KEY ("season_id", "player_id", "is_regular_season")
        REFERENCES "season_player_stats"("season_id", "player_id", "is_regular_season")
);

CREATE TABLE IF NOT EXISTS "season_player_rushing_stats" (
    "season_id" INT NOT NULL,
    "player_id" INT NOT NULL,
    "is_regular_season" BOOL NOT NULL,
    "gp" INT NOT NULL,
    "car" INT NOT NULL,
    "yds" INT NOT NULL,
    "avg" NUMERIC(6,2) NOT NULL,
    "td" INT NOT NULL,
    "lng" INT NOT NULL,
    "fd" INT NOT NULL,
    "fum" INT NOT NULL,
    "lst" INT NOT NULL,
    PRIMARY KEY ("season_id", "player_id", "is_regular_season"),
    FOREIGN KEY ("season_id", "player_id", "is_regular_season")
        REFERENCES "season_player_stats"("season_id", "player_id", "is_regular_season")
);

CREATE TABLE IF NOT EXISTS "season_player_passing_stats" (
    "season_id" INT NOT NULL,
    "player_id" INT NOT NULL,
    "is_regular_season" BOOL NOT NULL,
    "gp" INT NOT NULL,
    "cmp" INT NOT NULL,
    "att" INT NOT NULL,
    "cmp_pct" NUMERIC(5,2) NOT NULL,
    "yds" INT NOT NULL,
    "avg" NUMERIC(6,2) NOT NULL,
    "td" INT NOT NULL,
    "int_" INT NOT NULL,
    "lng" INT NOT NULL,
    "sack" INT NOT NULL,
    "rtg" NUMERIC(5,2) NOT NULL,
    "qbr" NUMERIC(5,2) NOT NULL,
    PRIMARY KEY ("season_id", "player_id", "is_regular_season"),
    FOREIGN KEY ("season_id", "player_id", "is_regular_season")
        REFERENCES "season_player_stats"("season_id", "player_id", "is_regular_season")
);

CREATE TABLE IF NOT EXISTS "season_player_return_stats" (
    "season_id" INT NOT NULL,
    "player_id" INT NOT NULL,
    "is_regular_season" BOOL NOT NULL,
    "gp" INT NOT NULL,
    "p_att" INT NOT NULL,
    "p_yds" INT NOT NULL,
    "p_td" INT NOT NULL,
    "p_fc" INT NOT NULL,
    "p_lng" INT NOT NULL,
    "k_att" INT NOT NULL,
    "k_yds" INT NOT NULL,
    "k_td" INT NOT NULL,
    "k_fc" INT NOT NULL,
    "k_lng" INT NOT NULL,

    PRIMARY KEY ("season_id", "player_id", "is_regular_season"),
    FOREIGN KEY ("season_id", "player_id", "is_regular_season")
        REFERENCES "season_player_stats"("season_id", "player_id", "is_regular_season")
);

CREATE TABLE IF NOT EXISTS "season_player_defense_stats" (
    "season_id" INT NOT NULL,
    "player_id" INT NOT NULL,
    "is_regular_season" BOOL NOT NULL,
    "gp" INT NOT NULL,
    "tot" INT NOT NULL,
    "solo" INT NOT NULL,
    "ast" INT NOT NULL,
    "sack" INT NOT NULL,
    "ff" INT NOT NULL,
    "fr" INT NOT NULL,
    "yds" INT NOT NULL,
    "int_" INT NOT NULL,
    "avg" NUMERIC(6,2) NOT NULL,
    "td" INT NOT NULL,
    "lng" INT NOT NULL,
    "pd" INT NOT NULL,
    "stf" INT NOT NULL,
    "stfyds" INT NOT NULL,
    "kb" INT NOT NULL,
    PRIMARY KEY ("season_id", "player_id", "is_regular_season"),
    FOREIGN KEY ("season_id", "player_id", "is_regular_season")
        REFERENCES "season_player_stats"("season_id", "player_id", "is_regular_season")
);

CREATE TABLE IF NOT EXISTS "season_player_scoring_stats" (
    "season_id" INT NOT NULL,
    "player_id" INT NOT NULL,
    "is_regular_season" BOOL NOT NULL,
    "gp" INT NOT NULL,
    "pass" INT NOT NULL,
    "rush" INT NOT NULL,
    "rec" INT NOT NULL,
    "ret" INT NOT NULL,
    "td" INT NOT NULL,
    "two_pt" INT NOT NULL,
    "pat" INT NOT NULL,
    "fg" INT NOT NULL,
    "pts" INT NOT NULL,
    PRIMARY KEY ("season_id", "player_id", "is_regular_season"),
    FOREIGN KEY ("season_id", "player_id", "is_regular_season")
        REFERENCES "season_player_stats"("season_id", "player_id", "is_regular_season")
);

CREATE TABLE IF NOT EXISTS "season_player_kicking_stats" (
    "season_id" INT NOT NULL,
    "player_id" INT NOT NULL,
    "is_regular_season" BOOL NOT NULL,
    "gp" INT NOT NULL,
    "fg" INT NOT NULL,
    "fg_pct" NUMERIC(5,2) NOT NULL,
    "fgm_1_19" INT NOT NULL,
    "fgm_20_29" INT NOT NULL,
    "fgm_30_39" INT NOT NULL,
    "fgm_40_49" INT NOT NULL,
    "fgm_50_plus" INT NOT NULL,
    "lng" INT NOT NULL,
    "xpm" INT NOT NULL,
    "xpa" INT NOT NULL,
    "pts" INT NOT NULL,
    PRIMARY KEY ("season_id", "player_id", "is_regular_season"),
    FOREIGN KEY ("season_id", "player_id", "is_regular_season")
        REFERENCES "season_player_stats"("season_id", "player_id", "is_regular_season")
);

CREATE TABLE IF NOT EXISTS "season_player_punting_stats" (
    "season_id" INT NOT NULL,
    "player_id" INT NOT NULL,
    "is_regular_season" BOOL NOT NULL,
    "gp" INT NOT NULL,
    "punts" INT NOT NULL,
    "avg" NUMERIC(6,2) NOT NULL,
    "lng" INT NOT NULL,
    "yds" INT NOT NULL,
    "tb" INT NOT NULL,
    "tb_pct" NUMERIC(5,2) NOT NULL,
    "in20" INT NOT NULL,
    "in20_pct" NUMERIC(5,2) NOT NULL,
    "att" INT NOT NULL,
    "att_yds" INT NOT NULL,
    "att_avg" NUMERIC(6,2) NOT NULL,
    "net" NUMERIC(6,2) NOT NULL,
    PRIMARY KEY ("season_id", "player_id", "is_regular_season"),
    FOREIGN KEY ("season_id", "player_id", "is_regular_season")
        REFERENCES "season_player_stats"("season_id", "player_id", "is_regular_season")
);

CREATE TABLE IF NOT EXISTS "game_player_stats" (
    "player_id" INT NOT NULL,
    "game_id" INT NOT NULL,

    PRIMARY KEY ("player_id", "game_id"),

    FOREIGN KEY ("player_id") REFERENCES "player"("player_id"),
    FOREIGN KEY ("game_id") REFERENCES "game"("game_id")
);

CREATE TABLE IF NOT EXISTS "game_player_passing_stats" (
    "player_id" INT,
    "game_id" INT,

    "completions" INT NOT NULL,
    "attempts" INT NOT NULL,
    "yards" INT NOT NULL,
    "touchdowns" INT NOT NULL,
    "interceptions" INT NOT NULL,
    "sacks" INT NOT NULL,
    "qbr" NUMERIC(5,2) NOT NULL,
    "rtg" NUMERIC(5,2) NOT NULL,

    PRIMARY KEY ("player_id", "game_id"),

    FOREIGN KEY ("player_id", "game_id")
        REFERENCES "game_player_stats"("player_id", "game_id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "game_player_rushing_stats" (
    "player_id" INT NOT NULL,
    "game_id" INT NOT NULL,

    "carries" INT NOT NULL,
    "yards" INT NOT NULL,
    "touchdowns" INT NOT NULL,
    "long_run" INT NOT NULL,

    PRIMARY KEY ("player_id", "game_id"),

    FOREIGN KEY ("player_id", "game_id")
        REFERENCES "game_player_stats"("player_id", "game_id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "game_player_receiving_stats" (
    "player_id" INT NOT NULL,
    "game_id" INT NOT NULL,

    "receptions" INT NOT NULL,
    "yards" INT NOT NULL,
    "touchdowns" INT NOT NULL,
    "long_reception" INT NOT NULL,
    "targets" INT NOT NULL,

    PRIMARY KEY ("player_id", "game_id"),

    FOREIGN KEY ("player_id", "game_id")
        REFERENCES "game_player_stats"("player_id", "game_id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "game_player_kicking_stats" (
    "player_id" INT NOT NULL,
    "game_id" INT NOT NULL,

    "field_goals_made" INT NOT NULL,
    "field_goals_attempted" INT NOT NULL,
    "longest_fg" INT NOT NULL,
    "extra_points" INT NOT NULL,
    "points" INT NOT NULL,

    PRIMARY KEY ("player_id", "game_id"),

    FOREIGN KEY ("player_id", "game_id")
        REFERENCES "game_player_stats"("player_id", "game_id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "game_player_punting_stats" (
    "player_id" INT NOT NULL,
    "game_id" INT NOT NULL,

    "punts" INT NOT NULL,
    "yards" INT NOT NULL,
    "touchbacks" INT NOT NULL,
    "inside_20" INT NOT NULL,
    "long_punt" INT NOT NULL,

    PRIMARY KEY ("player_id", "game_id"),

    FOREIGN KEY ("player_id", "game_id")
        REFERENCES "game_player_stats"("player_id", "game_id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "game_player_return_stats" (
    "player_id" INT NOT NULL,
    "game_id" INT NOT NULL,

    "punt_returns" INT NOT NULL,
    "punt_return_yards" INT NOT NULL,
    "punt_return_td" INT NOT NULL,
    "punt_long" INT NOT NULL,

    "kick_returns" INT NOT NULL,
    "kick_return_yards" INT NOT NULL,
    "kick_return_td" INT NOT NULL,
    "kick_long" INT NOT NULL,

    PRIMARY KEY ("player_id", "game_id"),

    FOREIGN KEY ("player_id", "game_id")
        REFERENCES "game_player_stats"("player_id", "game_id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "game_player_interception_stats" (
    "player_id" INT NOT NULL,
    "game_id" INT NOT NULL,

    "interceptions" INT NOT NULL,
    "yards" INT NOT NULL,
    "touchdowns" INT NOT NULL,

    PRIMARY KEY ("player_id", "game_id"),

    FOREIGN KEY ("player_id", "game_id")
        REFERENCES "game_player_stats"("player_id", "game_id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "game_player_fumble_stats" (
    "player_id" INT NOT NULL,
    "game_id" INT NOT NULL,

    "fumbles" INT NOT NULL,
    "fumbles_lost" INT NOT NULL,
    "fumbles_recovered" INT NOT NULL,

    PRIMARY KEY ("player_id", "game_id"),

    FOREIGN KEY ("player_id", "game_id")
        REFERENCES "game_player_stats"("player_id", "game_id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "game_player_defense_stats" (
    "player_id" INT NOT NULL,
    "game_id" INT NOT NULL,

    "total_tackles" INT NOT NULL,
    "solo_tackles" INT NOT NULL,
    "sacks" INT NOT NULL,
    "tackles_for_loss" INT NOT NULL,
    "passes_defended" INT NOT NULL,
    "qb_hits" INT NOT NULL,
    "touchdowns" INT NOT NULL,

    PRIMARY KEY ("player_id", "game_id"),

    FOREIGN KEY ("player_id", "game_id")
        REFERENCES "game_player_stats"("player_id", "game_id")
        ON DELETE CASCADE
);